# Generated by Django 2.2 on 2020-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyManager', '0002_auto_20200316_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='verify_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='最后验证时间'),
        ),
    ]
