# Generated by Django 2.2 on 2020-03-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyManager', '0004_auto_20200317_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='http',
            field=models.SmallIntegerField(choices=[(-1, '未验证'), (0, '不支持'), (1, '支持')], default=-1, verbose_name='HTTP'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='https',
            field=models.SmallIntegerField(choices=[(-1, '未验证'), (0, '不支持'), (1, '支持')], default=-1, verbose_name='HTTPS'),
        ),
    ]
