# Generated by Django 2.2 on 2020-03-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards_name', models.CharField(max_length=100)),
                ('prize', models.CharField(blank=True, max_length=540, null=True)),
                ('nominate', models.CharField(blank=True, max_length=540, null=True)),
            ],
            options={
                'verbose_name': '奖项',
                'verbose_name_plural': '奖项',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': '身份',
                'verbose_name_plural': '身份',
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('user_level', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=18, null=True)),
                ('gender', models.SmallIntegerField(default=0)),
                ('vipInfo', models.CharField(default='', max_length=19)),
                ('vipType', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': '评论者',
                'verbose_name_plural': '评论者',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='名字')),
                ('image', models.ImageField(default='person/default.png', upload_to='uploadtemp')),
                ('foreign_name', models.CharField(max_length=40, verbose_name='国外名')),
                ('birth_place', models.CharField(blank=True, max_length=45, null=True, verbose_name='出身地')),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('national', models.CharField(blank=True, max_length=15, null=True, verbose_name='名族')),
                ('nationality', models.CharField(blank=True, max_length=15, null=True, verbose_name='国籍')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='介绍')),
                ('identity', models.ManyToManyField(related_name='person', to='movieManager.Identity')),
            ],
            options={
                'verbose_name': '人物',
                'verbose_name_plural': '人物',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('movie_name', models.CharField(max_length=24)),
                ('image', models.ImageField(default='movie/default.png', upload_to='uploadtemp')),
                ('score', models.FloatField(default=0.0)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('release_time', models.DateField()),
                ('release_area', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('actor', models.ManyToManyField(related_name='actor_movie', to='movieManager.Person')),
                ('awards', models.ManyToManyField(related_name='awards_movie', to='movieManager.Awards')),
                ('category', models.ManyToManyField(related_name='ccategory_movie', to='movieManager.Category')),
                ('lead_director', models.ManyToManyField(related_name='lead_director_movie', to='movieManager.Person')),
                ('vice_director', models.ManyToManyField(related_name='vice_director_movie', to='movieManager.Person')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=20, unique=True)),
                ('start_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('score', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_comment', to='movieManager.Movie')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_comment', to='movieManager.Viewer')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
